
  create table "public"."chapters" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "number" smallint not null,
    "fragment" text,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" text,
    "updated_at" text
      );


alter table "public"."chapters" enable row level security;


  create table "public"."insignia" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "description" text not null,
    "image" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text
      );


alter table "public"."insignia" enable row level security;


  create table "public"."mission_progression" (
    "id" uuid not null default gen_random_uuid(),
    "team_id" bigint not null,
    "mission_id" uuid not null,
    "photo" text,
    "status" boolean not null,
    "fecha" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text
      );


alter table "public"."mission_progression" enable row level security;


  create table "public"."missions" (
    "id" uuid not null default gen_random_uuid(),
    "id_chapter" uuid,
    "marker_image" text,
    "points" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text
      );


alter table "public"."missions" enable row level security;


  create table "public"."roles" (
    "id" uuid not null default gen_random_uuid(),
    "type" text not null,
    "deleted_at" text,
    "updated_at" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."roles" enable row level security;


  create table "public"."schools" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "color" text,
    "points" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text
      );


alter table "public"."schools" enable row level security;


  create table "public"."team_insignia" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text,
    "team_id" bigint not null,
    "insignia_id" uuid not null
      );


alter table "public"."team_insignia" enable row level security;


  create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "leader_id" uuid not null,
    "school_id" uuid not null,
    "points" bigint,
    "level" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text
      );


alter table "public"."teams" enable row level security;


  create table "public"."usuarios" (
    "id" uuid not null,
    "alias" text not null,
    "nombre" text not null,
    "apellidos" text,
    "role_id" uuid,
    "school_id" uuid,
    "team_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" text,
    "deleted_at" text
      );


alter table "public"."usuarios" enable row level security;

CREATE UNIQUE INDEX chapter_pkey ON public.chapters USING btree (id);

CREATE UNIQUE INDEX insignia_pkey ON public.insignia USING btree (id);

CREATE UNIQUE INDEX mission_progression_pkey ON public.mission_progression USING btree (id);

CREATE UNIQUE INDEX missions_pkey ON public.missions USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX school_pkey ON public.schools USING btree (id);

CREATE UNIQUE INDEX team_insignia_pkey ON public.team_insignia USING btree (team_id, insignia_id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX usuarios_alias_key ON public.usuarios USING btree (alias);

CREATE UNIQUE INDEX usuarios_pkey ON public.usuarios USING btree (id);

alter table "public"."chapters" add constraint "chapter_pkey" PRIMARY KEY using index "chapter_pkey";

alter table "public"."insignia" add constraint "insignia_pkey" PRIMARY KEY using index "insignia_pkey";

alter table "public"."mission_progression" add constraint "mission_progression_pkey" PRIMARY KEY using index "mission_progression_pkey";

alter table "public"."missions" add constraint "missions_pkey" PRIMARY KEY using index "missions_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."schools" add constraint "school_pkey" PRIMARY KEY using index "school_pkey";

alter table "public"."team_insignia" add constraint "team_insignia_pkey" PRIMARY KEY using index "team_insignia_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."usuarios" add constraint "usuarios_pkey" PRIMARY KEY using index "usuarios_pkey";

alter table "public"."mission_progression" add constraint "mission_progression_mission_id_fkey" FOREIGN KEY (mission_id) REFERENCES public.missions(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."mission_progression" validate constraint "mission_progression_mission_id_fkey";

alter table "public"."mission_progression" add constraint "mission_progression_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."mission_progression" validate constraint "mission_progression_team_id_fkey";

alter table "public"."missions" add constraint "missions_id_chapter_fkey" FOREIGN KEY (id_chapter) REFERENCES public.chapters(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."missions" validate constraint "missions_id_chapter_fkey";

alter table "public"."team_insignia" add constraint "team_insignia_insignia_id_fkey" FOREIGN KEY (insignia_id) REFERENCES public.insignia(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."team_insignia" validate constraint "team_insignia_insignia_id_fkey";

alter table "public"."team_insignia" add constraint "team_insignia_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."team_insignia" validate constraint "team_insignia_team_id_fkey";

alter table "public"."teams" add constraint "teams_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES public.usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."teams" validate constraint "teams_leader_id_fkey";

alter table "public"."teams" add constraint "teams_school_id_fkey" FOREIGN KEY (school_id) REFERENCES public.schools(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."teams" validate constraint "teams_school_id_fkey";

alter table "public"."usuarios" add constraint "usuarios_alias_key" UNIQUE using index "usuarios_alias_key";

alter table "public"."usuarios" add constraint "usuarios_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."usuarios" validate constraint "usuarios_id_fkey";

alter table "public"."usuarios" add constraint "usuarios_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."usuarios" validate constraint "usuarios_role_id_fkey";

alter table "public"."usuarios" add constraint "usuarios_school_id_fkey" FOREIGN KEY (school_id) REFERENCES public.schools(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."usuarios" validate constraint "usuarios_school_id_fkey";

alter table "public"."usuarios" add constraint "usuarios_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."usuarios" validate constraint "usuarios_team_id_fkey";

grant delete on table "public"."chapters" to "anon";

grant insert on table "public"."chapters" to "anon";

grant references on table "public"."chapters" to "anon";

grant select on table "public"."chapters" to "anon";

grant trigger on table "public"."chapters" to "anon";

grant truncate on table "public"."chapters" to "anon";

grant update on table "public"."chapters" to "anon";

grant delete on table "public"."chapters" to "authenticated";

grant insert on table "public"."chapters" to "authenticated";

grant references on table "public"."chapters" to "authenticated";

grant select on table "public"."chapters" to "authenticated";

grant trigger on table "public"."chapters" to "authenticated";

grant truncate on table "public"."chapters" to "authenticated";

grant update on table "public"."chapters" to "authenticated";

grant delete on table "public"."chapters" to "service_role";

grant insert on table "public"."chapters" to "service_role";

grant references on table "public"."chapters" to "service_role";

grant select on table "public"."chapters" to "service_role";

grant trigger on table "public"."chapters" to "service_role";

grant truncate on table "public"."chapters" to "service_role";

grant update on table "public"."chapters" to "service_role";

grant delete on table "public"."insignia" to "anon";

grant insert on table "public"."insignia" to "anon";

grant references on table "public"."insignia" to "anon";

grant select on table "public"."insignia" to "anon";

grant trigger on table "public"."insignia" to "anon";

grant truncate on table "public"."insignia" to "anon";

grant update on table "public"."insignia" to "anon";

grant delete on table "public"."insignia" to "authenticated";

grant insert on table "public"."insignia" to "authenticated";

grant references on table "public"."insignia" to "authenticated";

grant select on table "public"."insignia" to "authenticated";

grant trigger on table "public"."insignia" to "authenticated";

grant truncate on table "public"."insignia" to "authenticated";

grant update on table "public"."insignia" to "authenticated";

grant delete on table "public"."insignia" to "service_role";

grant insert on table "public"."insignia" to "service_role";

grant references on table "public"."insignia" to "service_role";

grant select on table "public"."insignia" to "service_role";

grant trigger on table "public"."insignia" to "service_role";

grant truncate on table "public"."insignia" to "service_role";

grant update on table "public"."insignia" to "service_role";

grant delete on table "public"."mission_progression" to "anon";

grant insert on table "public"."mission_progression" to "anon";

grant references on table "public"."mission_progression" to "anon";

grant select on table "public"."mission_progression" to "anon";

grant trigger on table "public"."mission_progression" to "anon";

grant truncate on table "public"."mission_progression" to "anon";

grant update on table "public"."mission_progression" to "anon";

grant delete on table "public"."mission_progression" to "authenticated";

grant insert on table "public"."mission_progression" to "authenticated";

grant references on table "public"."mission_progression" to "authenticated";

grant select on table "public"."mission_progression" to "authenticated";

grant trigger on table "public"."mission_progression" to "authenticated";

grant truncate on table "public"."mission_progression" to "authenticated";

grant update on table "public"."mission_progression" to "authenticated";

grant delete on table "public"."mission_progression" to "service_role";

grant insert on table "public"."mission_progression" to "service_role";

grant references on table "public"."mission_progression" to "service_role";

grant select on table "public"."mission_progression" to "service_role";

grant trigger on table "public"."mission_progression" to "service_role";

grant truncate on table "public"."mission_progression" to "service_role";

grant update on table "public"."mission_progression" to "service_role";

grant delete on table "public"."missions" to "anon";

grant insert on table "public"."missions" to "anon";

grant references on table "public"."missions" to "anon";

grant select on table "public"."missions" to "anon";

grant trigger on table "public"."missions" to "anon";

grant truncate on table "public"."missions" to "anon";

grant update on table "public"."missions" to "anon";

grant delete on table "public"."missions" to "authenticated";

grant insert on table "public"."missions" to "authenticated";

grant references on table "public"."missions" to "authenticated";

grant select on table "public"."missions" to "authenticated";

grant trigger on table "public"."missions" to "authenticated";

grant truncate on table "public"."missions" to "authenticated";

grant update on table "public"."missions" to "authenticated";

grant delete on table "public"."missions" to "service_role";

grant insert on table "public"."missions" to "service_role";

grant references on table "public"."missions" to "service_role";

grant select on table "public"."missions" to "service_role";

grant trigger on table "public"."missions" to "service_role";

grant truncate on table "public"."missions" to "service_role";

grant update on table "public"."missions" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."schools" to "anon";

grant insert on table "public"."schools" to "anon";

grant references on table "public"."schools" to "anon";

grant select on table "public"."schools" to "anon";

grant trigger on table "public"."schools" to "anon";

grant truncate on table "public"."schools" to "anon";

grant update on table "public"."schools" to "anon";

grant delete on table "public"."schools" to "authenticated";

grant insert on table "public"."schools" to "authenticated";

grant references on table "public"."schools" to "authenticated";

grant select on table "public"."schools" to "authenticated";

grant trigger on table "public"."schools" to "authenticated";

grant truncate on table "public"."schools" to "authenticated";

grant update on table "public"."schools" to "authenticated";

grant delete on table "public"."schools" to "service_role";

grant insert on table "public"."schools" to "service_role";

grant references on table "public"."schools" to "service_role";

grant select on table "public"."schools" to "service_role";

grant trigger on table "public"."schools" to "service_role";

grant truncate on table "public"."schools" to "service_role";

grant update on table "public"."schools" to "service_role";

grant delete on table "public"."team_insignia" to "anon";

grant insert on table "public"."team_insignia" to "anon";

grant references on table "public"."team_insignia" to "anon";

grant select on table "public"."team_insignia" to "anon";

grant trigger on table "public"."team_insignia" to "anon";

grant truncate on table "public"."team_insignia" to "anon";

grant update on table "public"."team_insignia" to "anon";

grant delete on table "public"."team_insignia" to "authenticated";

grant insert on table "public"."team_insignia" to "authenticated";

grant references on table "public"."team_insignia" to "authenticated";

grant select on table "public"."team_insignia" to "authenticated";

grant trigger on table "public"."team_insignia" to "authenticated";

grant truncate on table "public"."team_insignia" to "authenticated";

grant update on table "public"."team_insignia" to "authenticated";

grant delete on table "public"."team_insignia" to "service_role";

grant insert on table "public"."team_insignia" to "service_role";

grant references on table "public"."team_insignia" to "service_role";

grant select on table "public"."team_insignia" to "service_role";

grant trigger on table "public"."team_insignia" to "service_role";

grant truncate on table "public"."team_insignia" to "service_role";

grant update on table "public"."team_insignia" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."usuarios" to "anon";

grant insert on table "public"."usuarios" to "anon";

grant references on table "public"."usuarios" to "anon";

grant select on table "public"."usuarios" to "anon";

grant trigger on table "public"."usuarios" to "anon";

grant truncate on table "public"."usuarios" to "anon";

grant update on table "public"."usuarios" to "anon";

grant delete on table "public"."usuarios" to "authenticated";

grant insert on table "public"."usuarios" to "authenticated";

grant references on table "public"."usuarios" to "authenticated";

grant select on table "public"."usuarios" to "authenticated";

grant trigger on table "public"."usuarios" to "authenticated";

grant truncate on table "public"."usuarios" to "authenticated";

grant update on table "public"."usuarios" to "authenticated";

grant delete on table "public"."usuarios" to "service_role";

grant insert on table "public"."usuarios" to "service_role";

grant references on table "public"."usuarios" to "service_role";

grant select on table "public"."usuarios" to "service_role";

grant trigger on table "public"."usuarios" to "service_role";

grant truncate on table "public"."usuarios" to "service_role";

grant update on table "public"."usuarios" to "service_role";


  create policy "Enable read access for all users"
  on "public"."schools"
  as permissive
  for select
  to public
using (true);



